apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-tomcat-app
  template:
    metadata:
      labels:
        app: my-tomcat-app # the label for the pods and the deployments
    spec:
      containers:
      - name: my-tomcat-app
        image: statelesscontreg.azurecr.io/my-tomcat-app:latest # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # the application listens to this port
        volumeMounts:
        - mountPath: "/usr/share/pvc/data"
          name: stateless-pvc-claim
  volumeClaimTemplates:
  - metadata:
      name: stateless-pvc-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: stateless-storage-class
      resources:
        requests:
          storage: 1Gi