apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: stateless-pvc-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: stateless-storage-class
  resources:
    requests:
      storage: 1Gi
# This is no longer required, as the PVC is created as part of 
# statefulset and associated it to POD